name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get LTW
        run: |
          apt update && apt install wget
          cd app_pojavlauncher/libs
          wget https://github.com/PojavLauncherTeam/LTW/releases/latest/download/ltw-release.aar

      - name: Get JRE 8
        run: |
          mkdir -p app_pojavlauncher/src/main/assets/components/jre
          cd app_pojavlauncher/src/main/assets/components/jre
          wget -q -O jre8-pojav.zip "https://down.wss.show/qjmkjl1/i/uv/iuvvqjmkjl1?cdn_sign=1767419131-91-0-62d1f835a8c107c0f37aed7dbda974db&exp=1200&response-content-disposition=attachment%3B%20filename%3D%22jre8-pojav.zip%22%3B%20filename%2A%3Dutf-8%27%27jre8-pojav.zip"
          unzip -q jre8-pojav.zip
          rm jre8-pojav.zip
          echo "JRE 8 downloaded and extracted"

      - name: Get JRE17
        run: |
          mkdir -p app_pojavlauncher/src/main/assets/components/jre-new
          cd app_pojavlauncher/src/main/assets/components/jre-new
          wget -q -O jre17-pojav.zip "https://down.wss.show/ias2mg5/i/uv/iuvwias2mg5?cdn_sign=1767419538-23-0-3c9d47c90fe27738b6be21816a5ca29b&exp=1200&response-content-disposition=attachment%3B%20filename%3D%22jre17-pojav.zip%22%3B%20filename%2A%3Dutf-8%27%27jre17-pojav.zip"
          unzip -q jre17-pojav.zip
          rm jre17-pojav.zip
          echo "JRE 17 downloaded and extracted"

      - name: Get JRE21
        run: |
          mkdir -p app_pojavlauncher/src/main/assets/components/jre-21
          cd app_pojavlauncher/src/main/assets/components/jre-21
          wget -q -O jre21-pojav.zip "https://down.wss.show/nsw3iud/i/uv/iuvwnsw3iud?cdn_sign=1767419415-59-0-1821781e6862d7bb528005d6f4afbeb5&exp=1200&response-content-disposition=attachment%3B%20filename%3D%22jre21-pojav.zip%22%3B%20filename%2A%3Dutf-8%27%27jre21-pojav.zip"
          unzip -q jre21-pojav.zip
          rm jre21-pojav.zip
          echo "JRE 21 downloaded and extracted"

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11"

      - name: Build JRE JAR files
        run: |
          ./scripts/languagelist_updater.sh

          mkdir out
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build --no-daemon

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Google Play .aab
        if: github.repository_owner == 'PojavLauncherTeam' && github.ref_name == 'v3_openjdk'
        run: |
          gradle :app_pojavlauncher:bundleGplay
          mv app_pojavlauncher/build/outputs/bundle/gplay/app_pojavlauncher-gplay.aab out/app-gplay.aab

      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :app_pojavlauncher:assembleDebug
          mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug.apk

      - name: Build APK without runtime
        run: |
          rm -rf app_pojavlauncher/src/main/assets/components/jre
          rm -rf app_pojavlauncher/src/main/assets/components/jre-new
          rm -rf app_pojavlauncher/src/main/assets/components/jre-21
          gradle assembleDebug
          mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug-noruntime.apk
          
      - name: Gen md5sums
        run: |
          md5sum out/app-debug.apk > out/app-debug.md5
          md5sum out/app-debug-noruntime.apk > out/app-debug-noruntime.md5

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: out/app-debug.*

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: out/app-gplay.aab

      - name: Upload onto the Google Play testing track
        continue-on-error: true
        if: github.repository_owner == 'PojavLauncherTeam' && github.ref_name == 'v3_openjdk'
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.GPLAY_SERVICE_JSON }}
          packageName: net.kdt.pojavlaunch
          releaseFiles: out/app-gplay.aab
          track: internal
          inAppUpdatePriority: 5

      - name: Upload APK (without runtime)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-noruntime
          path: out/app-debug-noruntime.*
